/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f2e1321d9a6ed31e0cdd748976585d4f)
interface __BaseEnv_Env {
	DB: D1Database;
	OPENROUTER_MODEL: "deepseek/deepseek-v4-flash";
	OPENROUTER_SITE_URL: "";
	OPENROUTER_APP_NAME: "Sitemap Crawl";
	AI_PROMPT_VERSION: "seo-analysis-v1";
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_MODEL" | "OPENROUTER_SITE_URL" | "OPENROUTER_APP_NAME" | "AI_PROMPT_VERSION" | "OPENROUTER_API_KEY">> {}
}
